name: Cohesion CI
on: [push, pull_request]
jobs:
  ci:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: requirements-dev.txt
      - name: Run CI
        run: |
          python -m pip install -e .
          python -m pip install -r requirements-dev.txt
          python -m flake8
          python -m pytest --cov
